### ISSUE TITLE
How to add new optionnal classes to build_debian_iso

### ISSUE THREAD

**Issue by eroussy** [seapath/build_debian_iso#102]
**The problem**
Currently, there are four optional classes: SEAPATH_KERBEROS, SEAPATH_RAID, SEAPATH_DBG and SEAPATH_COCKPIT.
The three first are set in `srv_fai_config/class/99-seapath` using fai flags. These fai flags are set in `etc_fai/grub.cfg` depending on the grub entry the user choose when flashing
This method is great because it allows to have only one FAI usb key that can install all these optional classes on demand.
However, it creates a **lot** of grub entry (2 power number of  optional classes).

On the other hand, the cockpit class is installed directly by writing its name in `srv_fai_config/class/99-seapath` (see README section about cockpit)

We need to have only one way to install optional classes.

**My proposition**
I think it is useful to keep the `SEAPATH_DBG` class in the grub entry, to be able to reinstall a debug version of SEAPATH in case something goes wrong.
But raid and kerberos classes should be choosen when building the iso (like cockpit class). It is not useful to choose them in the grub menu.
I think installing them by writing their name manually to the `srv_fai_config/class/99-seapath` file is the best option, but if you have a better idea, I'm interested.

**Comment by ebail** [comment]
Hi @insatomcat please share your opinion. Thanks

**Comment by insatomcat** [comment]
I find the "non-production" "packages" classes SEAPATH_DBG and SEAPATH_COCKPIT not that useful.
I say non-production because the debug packages and the cockpit packages are not suitable for production use (where ansible/snmp is the appropriate way to manage the servers).
For those classes, it's pretty easy to install the packages a posteriori (apt install...) so having those ready in the usb media is really just a "nice to have" in development.
Those classes should not have dedicated grub menu items.

The SEAPATH_KERBEROS may have some use in production, but right now, I don't think it's a problem if it does not have its own grub menu items either.

So my opinion is that:
- we can create a flag for each class in the 99-seapath file
- we should only have dedicated grub item for "non package" classes (RAID or NOT RAID) basically, because it impacts the disk_config
- the user can still add any class it wants to deploy by pressing "e" while selecting the grub item it wants, and adding the flags in FAI_FLAGS manually before booting

This would leave us with only 2 grub menu items, but would allow the user to manually choose DBG, COCKPIT, or KERBEROS if he/she needs.

**Comment by eroussy** [comment]
That seems great, I just have two remarks.
- I think it is good to keep a debug feature in the grub menu as it will be the most used feature in my opinion. Yes, the user can `apt update` all packages after the installation, but this class contains a lot of packages.
- I'm not sure having to press "e" in the grub menu to add non-production classes is convenient. I find it better to add the class names directly in `srv_fai_config/class/99-seapath`. In both cases, we should definitely have that documented.

**Comment by insatomcat** [comment]
standalone version + adding new classes will be greatly simplified with #105
