### ISSUE TITLE
systemctl commands don't apply on target

### ISSUE THREAD

**Issue by eroussy** [seapath/build_debian_iso#109]
Somes services are disabled by the scripts of build_debian_iso (corosync,pacemaker, systemd-netword-wait-online ... )
Theses commands all fail when flashing a machine with this error : 
"System has not been booted with systemd as init system (PID: 1). Can't operate"

**Steps to reproduce**
- Build a default debian image with `./build_iso.sh`
- Copy it on the usb key
- Boot the ubs key and your machine
- Wait the end of the FAI process to see the errors, particularly when applying `SEAPATH_COMMON/40-networking`, `SEAPATH_COMMON/60-misc` and `SEAPATH_HOST/61-misc`

**Comment by insatomcat** [comment]
It's just a normal warning since the nfsroot is working on a chrooted environment.
The script still works: the service are properly disabled (the link files in /etc/systemd/system are removed).

**Comment by dknueppe** [comment]
Pretty sure I ran into this issue as well. I think I fixed it by manually creating a symlink in the correct location on the target, since thats effectively whats done when you enable the service. By manually I mean, have a script that exucutes after the FAI installation has the files in place, rather then a script that has 'systemctl enable ...' in it.

**Comment by insatomcat** [comment]
We could remove this warning by replacing those "systemctl disable.." by "rm -f /etc/systemd/system/multi-user.target.wants/..."
But I was not fond of the idea of hardcoding the name of the target... that's why I prefered letting systemctl do its job.
Yes it creates a warning, but the associated commands are still run so it still does work.
We could also do some kind of "2>/dev/null" to hide the warning but once again since I know this warning is not a problem I tend not to care much about it.
