### ISSUE TITLE
FAI (re)installation may fail wiping the partitions

### ISSUE THREAD

**Issue by deribaucourt** [seapath/build_debian_iso#46]
![IMG_20230223_120907](https://user-images.githubusercontent.com/19970889/220891440-fae64844-5e7b-40ad-947e-f9c045a2333e.jpg)

It seems FAI first makes the list of partitions then deletes them in a loop. This is problematic with LVM since /dev/sda can contain /dev/vg1 so it is already destroyed.

Erasing the partition table before installation works (dd if=/dev/zero of=/dev/sda bs=1M count=1)

**Comment by ebail** [comment]
@insatomcat any opinon on that ?

**Comment by insatomcat** [comment]
My first though is that there's a even easier workaround: retry the installation a second time won't give the error.
On whether it can be fixed ... well that's tricky. It might be a bug or a misunderstood feature of FAI project.

The comments say the code is "Removing existing volume group if underlying devices will be modified".
https://github.com/faiproject/fai/blob/e75e2c1b619d0bfa8b01ba421f653de27682f88c/lib/setup-storage/Commands.pm#L743

I'm not quite sure why FAI needs to loop on the LV instead of wiping the whole disk (/dev/sdX), but there must be a reason, and so I'm not quite sure how to fix. 
Maybe it's worth opening an issue on their github?

**Comment by insatomcat** [comment]
#48 will solve this.
